### ISSUE TITLE
Some working, some not

### ISSUE THREAD

**Issue by ghost** [ttscoff/Slogger#276]
Hi,

I've just started working with DayOne and Slogger looks like a great tool.

I've installed everything and configured things, but I'm getting odd results.

The only plugins I've got are:
Twitter
Goodreads
Omnifocus
Flickr

Twitter and Omnifocus are working, but the other two are not finding anything, although I've specifically made changes to both in order to test.

Can I just get a view on my config for these, as perhaps I'm missing something?

```
GoodreadsLogger:
  description:
  - goodreads_save_image will save the book cover as the main image for the entry
  - goodreads_feed is a string containing the RSS feed for your read books
  - goodreads_star_posts will create a starred post for new books
  - 'goodreads_tags are tags you want to add to every entry, e.g. "#social #reading"'
  GoodreadsLogger_last_run: Thu Mar 13 14:31:03 2014
  goodreads_feed: https://www.goodreads.com/review/list_rss/10276588?key=c5a8367d446d910fff55591762227afb18f9877c&shelf=read
  goodreads_save_image: true
  goodreads_star_posts: false
  goodreads_tags: '#social #reading'
FlickrLogger:
  flickr_description:
  - Logs today's photos from Flickr.
  - flickr_ids is an array of one or more IDs
  - flickr_datetype can be the "upload" or "taken" date to be used
  - Get your Flickr ID at <http://idgettr.com/>
  - Get your Flickr API key at <http://www.flickr.com/services/apps/create/noncommercial/>
  FlickrLogger_last_run: Thu Mar 13 14:31:03 2014
  flickr_api_key: 5433e55a6591133c9e99ca7a8cb26640
  flickr_ids:
  - 12849518@N00
  flickr_datetype: upload
  flickr_tags: '#social #photo'
```

I've checked everything (in terms of urls and api keys, etc) and they all seem correct. I'm not seeing any errors from ./slogger

Any ideas?

Thanks
