### ISSUE TITLE
Pinboardlogger doesn't like my URL

### ISSUE THREAD

**Issue by oliverhaslam** [ttscoff/Slogger#305]
Hi all,

I've had a few issues getting Slogger to work but so far I've managed to overcome them all, bar one: Pinboardlogger throws an error when I give it my RSS URL.

My config:

``` yaml
PinboardLogger:
  pinboard_description:
  - Logs bookmarks for today from Pinboard.in.
  - pinboard_feeds is an array of one or more Pinboard RSS feeds
  - pinboard_digest true will group all new bookmarks into one post, false will split
    them into individual posts dated when the bookmark was created
  PinboardLogger_last_run: Wed May 14 22:22:33 2014
  pinboard_feeds: https://feeds.pinboard.in/rss/u:oliverhaslam
  pinboard_tags: '#social #bookmarks'
  pinboard_save_hashtags: true
  pinboard_digest: true
```

and the result:

> MacBook2008:Slogger-master oli$ ./slogger -o pinboardlogger
> Initializing Slogger v2.1 (2.1.0.11)...
>   22:33:23       PinboardLogger: Getting Pinboard bookmarks for 44 feeds
> /Users/oli/Slogger-master/plugins/pinboardlogger.rb:70:in `do_log': undefined method`each' for "https://feeds.pinboard.in/rss/u:oliverhaslam":String (NoMethodError)
>     from /Users/oli/Slogger-master/slogger.rb:283:in `block in run_plugins'
>     from /Users/oli/Slogger-master/slogger.rb:270:in`each'
>     from /Users/oli/Slogger-master/slogger.rb:270:in `run_plugins'
>     from /Users/oli/Slogger-master/slogger.rb:446:in`<top (required)>'
>     from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>     from ./slogger:18:in `<main>'
> MacBook2008:Slogger-master oli$ 

As far as I can tell, it's all configured correctly. Obviously not!

Any bright ideas?

Cheers.
