### ISSUE TITLE
LastFM COVERS date is off by 273 years...not pulling in covers either.

### ISSUE THREAD

**Issue by brianroach** [ttscoff/Slogger#376]
2 Centuries, 7 Decades, 3 years, 9 months, 1 week, and 4 days to be exact. 

It's pulling in the scrobbled track data just fine, just not getting the covers and logging it to the correct date.

![lastfm logger](https://cloud.githubusercontent.com/assets/9772694/8390671/9c21410c-1c56-11e5-9368-ea052f4c2107.jpg)

Here is what I have in my slogger_config file. Btw, even though I have the lastfmcovers.rb plugin enabled (and not the lastfmlogger.rb one) when I update the config, it still pulls in the LastFMLogger title as you can see below. 

```
LastFMLogger:
  lastfm_description:
  - Logs songs scrobbled for time period.
  - lastfm_user is your Last.fm username.
  - lastfm_feeds is an array that determines whether it grabs recent tracks, loved
    tracks, or both
  - lastfm_include_timestamps (true/false) will add a timestamp prefix based on @time_format
    to each song
  LastFMLogger_last_run: Fri Jun 26 22:18:30 2015
  lastfm_include_timestamps: true
  lastfm_user: ANODIGITAL
  lastfm_covers: true
  lastfm_chunk: ''
  lastfm_feeds:
  - recent
  - loved
  lastfm_tags: '#social #music'
```
